# Generated by Django 4.1.3 on 2022-11-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='text',
            field=models.TextField(default='default'),
        ),
    ]
