# Generated by Django 4.1.3 on 2022-11-23 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_response_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='submit',
            field=models.BooleanField(default=False),
        ),
    ]
